application:
  actions: actions
  web: web-src
  runtimeManifest:
    packages:
      aco-sfcc-starter-kit:
        license: Apache-2.0
        actions:
          # Please DO NOT DELETE this action; future functionalities planned for upcoming starter kit releases may stop working.
          info:
            function: actions/info/index.js
            web: 'yes'
            runtime: nodejs:22
            inputs:
              LOG_LEVEL: debug
            annotations:
              require-adobe-auth: true
              final: true
      spa:
        license: Apache-2.0
        actions:
          $include: ./actions/spa/actions.config.yaml
        inputs:
          $include: ./actions/inputs.yaml
      full-backoffice:
        license: Apache-2.0
        inputs:
          $include: ./actions/inputs.yaml
        actions:
          $include: ./actions/full/external/actions.config.yaml
      delta-backoffice:
        license: Apache-2.0
        inputs:
          $include: ./actions/inputs.yaml
        actions:
          $include: ./actions/delta/external/actions.config.yaml
        # triggers:
        #   everyMin:
        #     feed: /whisk.system/alarms/interval
        #     inputs:
        #       minutes: 60
        # rules:
        #   everyMinRule:
        #     trigger: everyMin
        #     action: delta-backoffice/consumer
      metadata-backoffice:
        license: Apache-2.0
        inputs:
          $include: ./actions/inputs.yaml
        actions:
          $include: ./actions/metadata/external/actions.config.yaml
      product-backoffice:
        license: Apache-2.0
        inputs:
          $include: ./actions/inputs.yaml
        actions:
          $include: ./actions/product/external/actions.config.yaml
      priceBook-backoffice:
        license: Apache-2.0
        inputs:
          $include: ./actions/inputs.yaml
        actions:
          $include: ./actions/price-book/external/actions.config.yaml

productDependencies:
  - code: COMMC
    minVersion: 2.4.4
    maxVersion: 3.0.0
