consumer:
  function: consumer/index.js
  web: 'no'
  runtime: nodejs:22
  annotations:
    require-adobe-auth: true
    final: true

sync:
  function: sync/index.js
  web: 'no'
  runtime: nodejs:22
  limits:
    timeout: 120000 # 2 minutes
  inputs:
    LOG_LEVEL: debug
    ACO_TENANT_ID: $ACO_TENANT_ID
    ACO_REGION: $ACO_REGION
    ACO_ENVIRONMENT_TYPE: $ACO_ENVIRONMENT_TYPE
    SFCC_API_BASE_URL: $SFCC_API_BASE_URL
    SFCC_REALM_ID: $SFCC_REALM_ID
    SFCC_INSTANCE_ID: $SFCC_INSTANCE_ID
    SFCC_ORGANIZATION_ID: $SFCC_ORGANIZATION_ID
    SFCC_AUTH_URL: $SFCC_AUTH_URL
    SFCC_CLIENT_ID: $SFCC_CLIENT_ID
    SFCC_CLIENT_SECRET: $SFCC_CLIENT_SECRET
    SFCC_SITE_ID: $SFCC_SITE_ID
    SFCC_LOCALES_TO_SYNC: $SFCC_LOCALES_TO_SYNC
    OAUTH_ORG_ID: $OAUTH_ORG_ID
    OAUTH_CLIENT_ID: $OAUTH_CLIENT_ID
    OAUTH_CLIENT_SECRET: $OAUTH_CLIENT_SECRET
    OAUTH_TECHNICAL_ACCOUNT_ID: $OAUTH_TECHNICAL_ACCOUNT_ID
    OAUTH_TECHNICAL_ACCOUNT_EMAIL: $OAUTH_TECHNICAL_ACCOUNT_EMAIL
    IO_MANAGEMENT_BASE_URL: $IO_MANAGEMENT_BASE_URL
    IO_CONSUMER_ID: $IO_CONSUMER_ID
    IO_PROJECT_ID: $IO_PROJECT_ID
    IO_WORKSPACE_ID: $IO_WORKSPACE_ID
    AIO_runtime_namespace: $AIO_RUNTIME_NAMESPACE
  annotations:
    require-adobe-auth: true
    final: true
